services:
  admin-panel:
    image: node:22-alpine
    container_name: admin-panel
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend

  backend:
    build:
      context: ../backend/backend
      dockerfile: Dockerfile
    container_name: admin-panel-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/admin_panel
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: admin-panel-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: admin_panel
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - admin_panel_db:/var/lib/postgresql/data

volumes:
  admin_panel_db: