server.port=${PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/admin_panel}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.default-schema=public

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=public
logging.level.org.flywaydb=DEBUG
jwt.secret=dUkvHBJ3IXx9LmKjagBtvQMmW2dGr9Qx1yrm0i6oFSxjtaMcaV7lCTeZ1AGsvumg
jwt.expiration=86400000

